"""add_task_registry_table

Revision ID: 6495666d07e4
Revises: 2aad51a773a9

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6495666d07e4'
down_revision: Union[str, None] = '2aad51a773a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_registry',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('human_readable_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_last_seen', 'task_registry', ['last_seen'], unique=False)
    op.create_index('idx_task_name_lookup', 'task_registry', ['name'], unique=False)
    op.create_index(op.f('ix_task_registry_name'), 'task_registry', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_registry_name'), table_name='task_registry')
    op.drop_index('idx_task_name_lookup', table_name='task_registry')
    op.drop_index('idx_last_seen', table_name='task_registry')
    op.drop_table('task_registry')
    # ### end Alembic commands ###
