"""add_task_daily_stats_table

Revision ID: 8ff8ccaebcba
Revises: 6495666d07e4

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ff8ccaebcba'
down_revision: Union[str, None] = '6495666d07e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_daily_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_executions', sa.Integer(), nullable=True),
    sa.Column('succeeded', sa.Integer(), nullable=True),
    sa.Column('failed', sa.Integer(), nullable=True),
    sa.Column('pending', sa.Integer(), nullable=True),
    sa.Column('retried', sa.Integer(), nullable=True),
    sa.Column('revoked', sa.Integer(), nullable=True),
    sa.Column('orphaned', sa.Integer(), nullable=True),
    sa.Column('avg_runtime', sa.Float(), nullable=True),
    sa.Column('min_runtime', sa.Float(), nullable=True),
    sa.Column('max_runtime', sa.Float(), nullable=True),
    sa.Column('p50_runtime', sa.Float(), nullable=True),
    sa.Column('p95_runtime', sa.Float(), nullable=True),
    sa.Column('p99_runtime', sa.Float(), nullable=True),
    sa.Column('first_execution', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_execution', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_date_lookup', 'task_daily_stats', ['date'], unique=False)
    op.create_index('idx_task_name_date_range', 'task_daily_stats', ['task_name', 'date'], unique=False)
    op.create_index('idx_unique_task_date', 'task_daily_stats', ['task_name', 'date'], unique=True)
    op.create_index(op.f('ix_task_daily_stats_date'), 'task_daily_stats', ['date'], unique=False)
    op.create_index(op.f('ix_task_daily_stats_task_name'), 'task_daily_stats', ['task_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_daily_stats_task_name'), table_name='task_daily_stats')
    op.drop_index(op.f('ix_task_daily_stats_date'), table_name='task_daily_stats')
    op.drop_index('idx_unique_task_date', table_name='task_daily_stats')
    op.drop_index('idx_task_name_date_range', table_name='task_daily_stats')
    op.drop_index('idx_date_lookup', table_name='task_daily_stats')
    op.drop_table('task_daily_stats')
    # ### end Alembic commands ###
