"""add_environments_table

Revision ID: d9f3a1e5c2b8
Revises: 2aad51a773a9

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9f3a1e5c2b8'
down_revision: Union[str, None] = '2aad51a773a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('queue_patterns', sa.JSON(), nullable=True),
    sa.Column('worker_patterns', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_env_active', 'environments', ['is_active'], unique=False)
    op.create_index('idx_env_default', 'environments', ['is_default'], unique=False)
    op.create_index(op.f('ix_environments_name'), 'environments', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_environments_name'), table_name='environments')
    op.drop_index('idx_env_default', table_name='environments')
    op.drop_index('idx_env_active', table_name='environments')
    op.drop_table('environments')
    # ### end Alembic commands ###
